export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOAD_REQUEST = 'USER_LOAD_REQUEST';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT = 'USER_LOGOUT';

export const EVENT_SEARCH_REQUEST = 'EVENT_SEARCH_REQUEST';
export const EVENT_SEARCH_SUCCESS = 'EVENT_SEARCH_SUCCESS';
export const EVENT_SEARCH_FAILURE = 'EVENT_SEARCH_FAILURE';